### PR TITLE
Deploy to Compute Instance script

### PR DESCRIPTION
**Pull request by yash-atreya**
Addresses issue #56

### CODE REVIEW

**Review by wuyasan — APPROVED** [review]
Looks Good

**Review by Soosi18 — COMMENTED** [review]
doesn't work well with multiple files in /src... does the string with the paths for all script files need a separator or something? i'm not really sure how this cli works

**Review by Soosi18 — APPROVED** [review]
Looks good!

**Review by bluemailbox — APPROVED** [review]
looks good

**Pull request merged**
