### PR TITLE
Tech Stack

### PR DESCRIPTION
**Pull request by yash-atreya**
```TechStack.md``` doc for requirements report

### CODE REVIEW

**Comment by yash-atreya** [comment]
Awaiting Review

**Review by bluemailbox — CHANGES_REQUESTED** [review]
Missing front end desc

**Review by Soosi18 — APPROVED** [review]
Good work. I don't think i'll be mentioning front end details in the actual report though.

**Review by bluemailbox — APPROVED** [review]
looks good

**Pull request merged**
