### PR TITLE
Gentle output

### PR DESCRIPTION
**Pull request by bluemailbox**

### CODE REVIEW

**Review by Soosi18 — APPROVED** [review]
good work!

**Comment by Soosi18** [comment]
Please add comments when you can!

**Comment by Soosi18** [comment]
updated gentle_output.py to have functions that allow me to test stuff easier

**Review by wuyasan — COMMENTED** [review]
Looks Good

**Comment by Soosi18** [comment]
thanks.

**Review by wuyasan — APPROVED** [review]

**Pull request merged**
