### PR TITLE
Meeting notes team agreement

### PR DESCRIPTION
**Pull request by bluemailbox**
added first meeting notes and updated team agreement

### CODE REVIEW

**Review by Soosi18 — CHANGES_REQUESTED** [review]
Could you convert the meeting notes to a markdown file for readability and ability to preview? Also, could you add the name of month in the file name for this meeting log and all logs moving forward? Thanks.

**Comment by bluemailbox** [comment]
made the suggested changes

**Review by Soosi18 — APPROVED** [review]
Thanks for making the requested changes!

**Comment by wuyasan** [comment]
Looks Good!

**Review by wuyasan — APPROVED** [review]
Looks Good!

**Pull request merged**
