### PR TITLE
Api-Spec

### PR DESCRIPTION
**Pull request by yash-atreya**
I have created the initial spec, I'm sure there will be changes and additions. Currently trying to get the server running on compute engine and set up the infrastructure by next week.

### CODE REVIEW

**Comment by yash-atreya** [comment]
The routes defined in the spec are mostly internal and not user-facing. 
Ultimately there will only be one ```GET``` the user sends, which contains info about the avatar selected, the language, and of course, the text file that is to be converted to speech.

**Review by Soosi18 — CHANGES_REQUESTED** [review]
I'm not sure if points 1 and 3 are really needed here. This is for Kukarella's use only, and they would already have the audio file and info on the selected avatar. I think returning the gentle output for debugging purposes and the generated video are the only two things required here. Would like to hear others' opinion on this.

**Comment by yash-atreya** [comment]
@Soosi18  I think ```1```is required until the integration with the kukarella UI is done as we still have to send the text to Kukarella's API and get the response back, and then use that for gentle. 
If we don't have 1 then the GUI will have to directly send the request to Kukarella, get the response, send that response to the gentle process. 
If we have ```1``` then we could just pass the response to gentle without the GUI in between.

As for ```3```, I wasn't sure how we were going to integrate their avatars, so just assumed that we'll have to store them ourselves.

**Comment by Soosi18** [comment]
That makes sense for ```1```, thanks for clarifying. When it comes to storing avatars, I'm not really sure myself, so we can keep ```3``` for now too.

**Review by Soosi18 — APPROVED** [review]
Good work!

**Comment by bluemailbox** [comment]
Yeah we'll require sending text to kukarella for the time being, since we're just working locally at the moment and we don't have kukarellas end point quite yet. We'll need to generate audio from kukarella prior in the future

as for 3, yeah its tbd on the avatar situation. I guess whatever the client wants to do, since the avatars will most likely be their property and not for free usage(?)

**Review by bluemailbox — APPROVED** [review]
Solid, I think the win32 package is just for finding directories if I'm correct?

**Pull request merged**
