### PR TITLE
Added Japanese Json generated by mfa

### PR DESCRIPTION
**Pull request by wuyasan**

### CODE REVIEW

**Comment by yash-atreya** [comment]
Do these file align successfully with MFA, are you able to create the video?

**Comment by wuyasan** [comment]
> Do these file align successfully with MFA, are you able to create the video?

Yes this is aligned with MFA and I'm trying with the video

**Review by yash-atreya — APPROVED** [review]

**Review by yash-atreya — APPROVED** [review]
Looks good!

**Review by bluemailbox — APPROVED** [review]
solid

**Pull request merged**
