### PR TITLE
Usability Tasks

### PR DESCRIPTION
**Pull request by Soosi18**

### CODE REVIEW

**Comment by Soosi18** [comment]
I'm not sure the task scenario for user group 2 is very good. If you guys have any suggestions/changes that you think would make it better, let me know!

**Review by yash-atreya — APPROVED** [review]

**Comment by yash-atreya** [comment]
I guess scenario 2 may not be required, but no harm in adding it.
Thinking of better use-cases

**Comment by Soosi18** [comment]
The animation quality is the only thing we need to test now, since we know input files will be validated on Kukarella's end. I added the 2nd scenario to cover both user groups, and to get user feedback on whether animations created with non-english voices is acceptable or not. Will clarify with the prof/TA in class next week if it makes sense to include it in the actual testing session.

**Comment by Soosi18** [comment]
was just looking for a better way to frame the wording for task scenario 2 since the current wording seems very forced.

**Review by wuyasan — APPROVED** [review]
Good Job

**Pull request merged**
